# Site Settings
title: WE Club 
tagline: Women Epitome of Success
email: support@nyctanthes.org
description: >
  WE - Woman Epitome of Service
url: "https://www.weclubsofindia.org"
permalink: pretty
favicon: /assets/img/favicon.jpg
# gh_sponsor: weclubsofindia
#hide_share_buttons: true

paginate: 5
paginate_path: "/blog/page:num"


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "We Club of NPST"
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true


markdown: kramdown
highlighter: rouge

# footer_menu: example_footer_menu

collections:
  members: 
    output: true    
    layout: member
    image: https://via.placeholder.com/800x600
    show_sidebar: false
    order:
      - kawal_rekhi.md
      - raxa-mehta.md
      - usha-joya.md
      - saroja_mekal.md
      - rajani_shetty.md
      - jyoti-jagasia.md
  sponsors: 
    output: true
    layout: sponsor
    image: https://via.placeholder.com/800x600
    show_sidebar: false